export const qBank = [
    {
        id: 1,
        question: "Do you watch F1?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "No",
    },
    {
        id: 2,
        question: "Do wear mostly black jeans?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "No",
    },
    {
        id: 3,
        question: "Who do you identify more with?",
        choices: ["Harry Potter", "Ron Weasly"],
        type: 'radio',
        correctAnswer: "Ron Weasly",
    },
    {
        id: 4,
        question: "Would you own a truck?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "No",
    },
    {
        id: 5,
        question: "Who do you identify more with?",
        choices: ["Timothee Chalamet", "Matthew McConaughey"],
        type: 'radio',
        correctAnswer: "Matthew McConaughey",
    },
    {
        id: 6,
        question: "Did you have an angsty teen phase?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "No",
    },
    {
        id: 7,
        question: "Team Edward or Team Jacob?",
        choices: ["Edward", "Jacob"],
        type: 'radio',
        correctAnswer: "Jacob",
    },
    {
        id: 8,
        question: "Do you have a baby face?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "Yes",
    },
    {
        id: 9,
        question: "Are you extroverted?",
        choices: ["Yes", "No"],
        type: 'radio',
        correctAnswer: "Yes",
    }
]
